sudo: required
addons:
  chrome: stable

language: node_js
node_js:
  - "8"

branches:
  only:
    - master
    - /^greenkeeper/.*$/

before_script:
  - npm install -g @angular/cli

script:
  - ng build --prod
  #- ng test
