sudo: required
addons:
  chrome: stable

language: node_js
node_js:
  - "stable"

branches:
  only:
    - master
    - /^greenkeeper/.*$/

before_script:
  - npm install -g @angular/cli
  # yarn update to latest version
  - curl -o- -L https://yarnpkg.com/install.sh | bash
  - export PATH="$HOME/.yarn/bin:$PATH"

script:
  - ng build --prod --aot
  - ng test
