sudo: required
addons:
  chrome: stable

language: node_js
node_js:
  - "stable"

branches:
  only:
    - master
    - /^greenkeeper/.*$/

before_script:
  - npm install -g @angular/cli

script:
  - ng build --prod --aot
  - ng test
